/* The following code was generated by JFlex 1.4.3 on 30.03.15 14:58 */

package com.github.kumaraman21.intellijbehave.peg;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.github.kumaraman21.intellijbehave.parser.IStoryPegElementType.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30.03.15 14:58 from the specification file
 * <tt>C:/Users/debritod/Work/Intellij-Idea/IntelliJBehave/src/com/github/kumaraman21/intellijbehave/peg/_StoryPegLexer.flex</tt>
 */
public class _StoryPegLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\10\1\1\1\2\22\0\1\1\1\5\4\20"+
    "\1\53\5\20\1\52\1\6\1\15\1\16\12\17\1\25\1\20\1\7"+
    "\1\20\1\11\1\20\1\14\1\43\1\57\1\12\1\63\1\45\1\12"+
    "\1\36\3\12\1\62\1\54\1\21\1\26\1\61\3\12\1\32\1\42"+
    "\2\12\1\40\2\12\1\4\4\20\1\13\1\20\1\24\1\12\1\33"+
    "\1\44\1\22\1\55\1\12\1\41\1\30\2\12\1\51\1\47\1\34"+
    "\1\35\1\50\1\12\1\27\1\37\1\23\1\12\1\31\1\12\1\46"+
    "\1\56\1\12\1\20\1\60\2\20\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\3\2\4\1\5\1\6\1\7"+
    "\1\4\1\10\1\4\1\11\1\7\1\12\7\7\1\13"+
    "\1\14\2\7\1\15\4\0\1\16\1\17\1\0\14\7"+
    "\1\20\1\21\1\22\1\0\1\22\1\0\7\7\1\23"+
    "\4\7\1\22\1\0\4\7\1\24\1\25\5\7\1\26"+
    "\1\0\1\27\2\7\1\30\5\7\1\0\4\7\1\31"+
    "\3\7\1\32\6\7\1\33\7\7\1\34\1\7\1\35"+
    "\1\36\1\7\1\37\1\7\1\40\2\7\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\320\0\320\0\u0138\0\64\0\u01d4\0\u0208"+
    "\0\64\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374"+
    "\0\64\0\64\0\u03a8\0\u03dc\0\64\0\u0138\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\64\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0"+
    "\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750"+
    "\0\u0784\0\u07b8\0\u0478\0\u07ec\0\u07ec\0\u0820\0\u0854\0\u0888"+
    "\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\320\0\u09c0\0\u09f4"+
    "\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94"+
    "\0\320\0\320\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0a90"+
    "\0\u0ccc\0\64\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04"+
    "\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\64"+
    "\0\u0fa4\0\u0fd8\0\u100c\0\u0ea0\0\u1040\0\u1074\0\u10a8\0\u10dc"+
    "\0\u1110\0\u1144\0\64\0\u1178\0\u11ac\0\u11e0\0\u1214\0\u1248"+
    "\0\u127c\0\u12b0\0\64\0\u12e4\0\320\0\64\0\u1318\0\64"+
    "\0\u134c\0\64\0\u1380\0\u13b4\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\2\1\12\1\13\1\14\1\15\1\10\1\16\1\17"+
    "\1\16\1\20\3\13\1\21\1\22\3\13\1\23\3\13"+
    "\1\24\1\13\1\25\1\13\1\26\1\27\1\13\1\30"+
    "\4\13\1\31\1\32\1\33\2\13\1\34\1\35\3\13"+
    "\65\0\1\3\1\4\2\5\62\0\1\5\64\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\4\13\1\0\24\13\2\0\4\13\1\0\3\13\6\0"+
    "\1\40\61\0\1\36\1\0\1\36\3\0\4\36\1\37"+
    "\1\36\1\0\4\36\1\0\24\36\2\0\4\36\1\0"+
    "\3\36\1\41\3\0\3\41\1\42\1\0\53\41\11\0"+
    "\1\43\56\0\1\13\1\0\1\36\3\0\2\13\1\36"+
    "\1\44\1\37\1\17\1\0\4\13\1\0\24\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\1\13\1\45\2\13"+
    "\1\0\24\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\3\13\1\46\1\0\24\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\5\13\1\47\16\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\4\13\1\0\2\13"+
    "\1\50\21\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\4\13\1\0\13\13\1\51\10\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\4\13\1\0\13\13\1\52\10\13"+
    "\2\0\4\13\1\0\1\53\2\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\6\13\1\54\15\13\2\0\1\13\1\55\2\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\20\13\1\56"+
    "\3\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\2\13\1\57\21\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\1\13\1\60\2\13\1\0\24\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\61\1\0\1\61\3\0"+
    "\4\61\1\0\1\61\1\0\4\61\1\0\24\61\2\0"+
    "\4\61\1\0\3\61\6\0\1\62\55\0\1\41\3\0"+
    "\4\41\1\0\1\63\52\41\1\64\3\0\4\64\1\0"+
    "\1\65\52\64\4\0\1\36\1\0\1\36\3\0\4\36"+
    "\1\37\1\66\1\0\4\36\1\0\24\36\2\0\4\36"+
    "\1\0\3\36\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\2\13\1\67\1\13\1\0"+
    "\24\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\1\13\1\70\22\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\1\13\1\71\2\13\1\0\24\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\4\13\1\0\3\13"+
    "\1\72\20\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\1\13\1\73\2\13\1\0\24\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\1\13\1\74\2\13\1\0\24\13"+
    "\2\0\4\13\1\0\3\13\4\0\1\13\1\0\1\36"+
    "\3\0\2\13\2\36\1\37\1\13\1\0\4\13\1\0"+
    "\24\13\2\0\4\13\1\0\1\13\1\75\1\13\4\0"+
    "\1\13\1\0\1\36\3\0\2\13\2\36\1\37\1\13"+
    "\1\0\4\13\1\0\16\13\1\76\5\13\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\2\13\1\77\1\13\1\0"+
    "\24\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\3\13"+
    "\1\100\1\0\24\13\2\0\4\13\1\0\3\13\4\0"+
    "\1\13\1\0\1\36\3\0\2\13\2\36\1\37\1\13"+
    "\1\0\4\13\1\0\24\13\2\0\1\13\1\101\2\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\24\13\2\0"+
    "\1\13\1\102\2\13\1\0\3\13\4\0\1\61\1\0"+
    "\1\61\3\0\4\61\1\37\1\61\1\0\4\61\1\0"+
    "\24\61\2\0\4\61\1\0\3\61\3\62\1\0\60\62"+
    "\1\64\3\0\4\64\1\0\1\103\52\64\4\0\1\36"+
    "\1\0\1\36\3\0\3\36\1\104\1\37\1\66\1\0"+
    "\4\36\1\0\24\36\2\0\4\36\1\0\3\36\4\0"+
    "\1\13\1\0\1\36\3\0\2\13\2\36\1\37\1\13"+
    "\1\0\3\13\1\105\1\0\24\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\4\13\1\0\1\13\1\106\22\13"+
    "\2\0\4\13\1\0\3\13\4\0\1\13\1\0\1\36"+
    "\3\0\2\13\2\36\1\37\1\13\1\0\4\13\1\0"+
    "\6\13\1\107\15\13\2\0\4\13\1\0\3\13\4\0"+
    "\1\13\1\0\1\36\3\0\2\13\2\36\1\37\1\13"+
    "\1\0\1\13\1\110\2\13\1\0\24\13\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\6\13\1\111"+
    "\15\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\6\13\1\112\15\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\17\13\1\113\4\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\1\13\1\114\2\13"+
    "\1\0\24\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\4\13\1\0\21\13\1\115\2\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\1\13\1\116\2\13\1\0\24\13"+
    "\2\0\4\13\1\0\3\13\4\0\1\13\1\0\1\36"+
    "\3\0\2\13\2\36\1\37\1\13\1\0\4\13\1\0"+
    "\7\13\1\117\14\13\2\0\4\13\1\0\3\13\1\64"+
    "\3\0\4\64\1\0\1\120\52\64\4\0\1\36\1\0"+
    "\1\36\3\0\4\36\1\37\1\121\1\0\4\36\1\0"+
    "\24\36\2\0\4\36\1\0\3\36\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\122\24\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\3\13\1\123\1\0\24\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\3\13\1\124\1\0\24\13\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\6\13\1\125"+
    "\15\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\1\126\23\13\2\0\4\13\1\0\3\13\4\0"+
    "\1\13\1\0\1\36\3\0\2\13\2\36\1\37\1\13"+
    "\1\0\4\13\1\0\1\13\1\127\22\13\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\22\13\1\130"+
    "\1\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\5\13\1\131\16\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\1\13\1\132\22\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\36\1\0\1\36\3\0"+
    "\3\36\1\133\1\37\1\121\1\0\4\36\1\0\24\36"+
    "\2\0\4\36\1\0\3\36\4\0\1\13\1\0\1\36"+
    "\3\0\2\13\2\36\1\37\1\13\1\0\2\13\1\134"+
    "\1\13\1\0\24\13\2\0\4\13\1\0\3\13\4\0"+
    "\1\13\1\0\1\36\3\0\2\13\2\36\1\37\1\13"+
    "\1\0\4\13\1\0\1\13\1\135\22\13\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\4\13\1\136"+
    "\17\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\1\13\1\137\2\36\1\37\1\13\1\0"+
    "\4\13\1\0\24\13\2\0\4\13\1\0\3\13\4\0"+
    "\1\13\1\0\1\36\3\0\2\13\2\36\1\37\1\13"+
    "\1\0\4\13\1\140\24\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\23\13\1\141\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\24\13\2\0"+
    "\2\13\1\142\1\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\1\13"+
    "\1\143\2\13\1\0\24\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\36\1\0\1\36\3\0\4\36\1\37\1\144"+
    "\1\0\4\36\1\0\24\36\2\0\4\36\1\0\3\36"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\2\13\1\145\21\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\4\13\1\0\2\13"+
    "\1\146\21\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\2\13\1\147\1\13\1\0\24\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\4\13\1\0\24\13\2\0\4\13"+
    "\1\0\2\13\1\150\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\1\13\1\151\2\13"+
    "\1\0\24\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\4\13\1\0\5\13\1\152\16\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\4\13\1\153\24\13\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\4\13\1\0\3\13\1\154"+
    "\20\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\7\13\1\155\14\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\7\13\1\156\14\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\4\13\1\0\24\13"+
    "\2\0\4\13\1\0\1\157\2\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\0\11\13\1\160\12\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\23\13\1\161\2\0\4\13"+
    "\1\0\3\13\4\0\1\13\1\0\1\36\3\0\2\13"+
    "\2\36\1\37\1\13\1\0\1\13\1\162\2\13\1\0"+
    "\24\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\4\13"+
    "\1\163\24\13\2\0\4\13\1\0\3\13\4\0\1\13"+
    "\1\0\1\36\3\0\2\13\2\36\1\37\1\13\1\0"+
    "\4\13\1\0\1\13\1\164\22\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\4\13\1\0\14\13\1\165\7\13"+
    "\2\0\4\13\1\0\3\13\4\0\1\13\1\0\1\36"+
    "\3\0\2\13\2\36\1\37\1\13\1\0\4\13\1\166"+
    "\24\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\1\13"+
    "\1\167\2\13\1\0\24\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\170\24\13\2\0\4\13\1\0"+
    "\3\13\4\0\1\13\1\0\1\36\3\0\2\13\2\36"+
    "\1\37\1\13\1\0\4\13\1\0\2\13\1\171\21\13"+
    "\2\0\4\13\1\0\3\13\4\0\1\13\1\0\1\36"+
    "\3\0\2\13\2\36\1\37\1\13\1\0\4\13\1\172"+
    "\24\13\2\0\4\13\1\0\3\13\4\0\1\13\1\0"+
    "\1\36\3\0\2\13\2\36\1\37\1\13\1\0\1\13"+
    "\1\173\2\13\1\0\24\13\2\0\4\13\1\0\3\13"+
    "\4\0\1\13\1\0\1\36\3\0\2\13\2\36\1\37"+
    "\1\13\1\0\4\13\1\0\11\13\1\174\12\13\2\0"+
    "\4\13\1\0\3\13\4\0\1\13\1\0\1\36\3\0"+
    "\2\13\2\36\1\37\1\13\1\0\4\13\1\175\24\13"+
    "\2\0\4\13\1\0\3\13";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5096];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\10\1\1\11\2\1\1\11"+
    "\7\1\2\11\2\1\1\11\4\0\1\1\1\11\1\0"+
    "\17\1\1\0\1\1\1\0\15\1\1\0\14\1\1\0"+
    "\1\11\10\1\1\0\4\1\1\11\12\1\1\11\7\1"+
    "\1\11\2\1\1\11\1\1\1\11\1\1\1\11\2\1"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _StoryPegLexer() {
    this((java.io.Reader)null);
  }


  public _StoryPegLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _StoryPegLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { return STORY_TOKEN_PUNCT;
          }
        case 34: break;
        case 7: 
          { return STORY_TOKEN_WORD;
          }
        case 35: break;
        case 13: 
          { return STORY_TOKEN_PIPE;
          }
        case 36: break;
        case 29: 
          { return STORY_TOKEN_DOT;
          }
        case 37: break;
        case 17: 
          { return STORY_TOKEN_COMMENT;
          }
        case 38: break;
        case 16: 
          { return STORY_TOKEN_PATH;
          }
        case 39: break;
        case 8: 
          { return STORY_TOKEN_AT;
          }
        case 40: break;
        case 30: 
          { return STORY_TOKEN_EXAMPLES;
          }
        case 41: break;
        case 25: 
          { return STORY_TOKEN_AFTER;
          }
        case 42: break;
        case 14: 
          { return STORY_TOKEN_DBRACKET_OPEN;
          }
        case 43: break;
        case 32: 
          { return STORY_TOKEN_LIFECYCLE;
          }
        case 44: break;
        case 26: 
          { return STORY_TOKEN_IP;
          }
        case 45: break;
        case 20: 
          { return STORY_TOKEN_WHEN;
          }
        case 46: break;
        case 15: 
          { return STORY_TOKEN_DBRACKET_CLOSE;
          }
        case 47: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 48: break;
        case 12: 
          { return STORY_TOKEN_AMPERSAND;
          }
        case 49: break;
        case 2: 
          { return STORY_TOKEN_SPACE;
          }
        case 50: break;
        case 28: 
          { return STORY_TOKEN_SCENARIO;
          }
        case 51: break;
        case 6: 
          { return STORY_TOKEN_BRACKET_CLOSE;
          }
        case 52: break;
        case 21: 
          { return STORY_TOKEN_THEN;
          }
        case 53: break;
        case 31: 
          { return STORY_TOKEN_NARRATIVE;
          }
        case 54: break;
        case 3: 
          { return STORY_TOKEN_NEWLINE;
          }
        case 55: break;
        case 18: 
          { return STORY_TOKEN_INJECT;
          }
        case 56: break;
        case 27: 
          { return STORY_TOKEN_BEFORE;
          }
        case 57: break;
        case 22: 
          { return STORY_TOKEN_USER_INJECT;
          }
        case 58: break;
        case 23: 
          { return STORY_TOKEN_META;
          }
        case 59: break;
        case 11: 
          { return STORY_TOKEN_COMMA;
          }
        case 60: break;
        case 5: 
          { return STORY_TOKEN_BRACKET_OPEN;
          }
        case 61: break;
        case 19: 
          { return STORY_TOKEN_AND;
          }
        case 62: break;
        case 24: 
          { return STORY_TOKEN_GIVEN;
          }
        case 63: break;
        case 9: 
          { return STORY_TOKEN_NUMBER;
          }
        case 64: break;
        case 33: 
          { return STORY_TOKEN_GIVEN_STORIES;
          }
        case 65: break;
        case 10: 
          { return STORY_TOKEN_COLON;
          }
        case 66: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
